site_name: HedgeDoc
site_url: https://docs.hedgedoc.org
repo_url: https://github.com/hedgedoc/hedgedoc
site_description: 'HedgeDoc Documentation'
site_author: 'HedgeDoc Developers'
nav:
  - Home: index.md
  - Installation:
      - 'Manual Installation': setup/manual-setup.md
      - 'Reverse Proxy': setup/reverse-proxy.md
      - Docker: setup/docker.md
      - Cloudron: setup/cloudron.md
      - Heroku: setup/heroku.md
      - LinuxServer: setup/docker-linuxserver.md
      - Yunohost: setup/yunohost.md
  - Guides:
      - Authentication:
          - LDAP: guides/auth/ldap-ad.md
          - OAuth: guides/auth/oauth.md
          - SAML : guides/auth/saml.md
          - SAML Keycloak : guides/auth/saml-keycloak.md
          - SAML Onelogin : guides/auth/saml-onelogin.md
          - GitHub: guides/auth/github.md
          - GitLab: guides/auth/gitlab-self-hosted.md
          - Keycloak: guides/auth/keycloak.md
          - NextCloud: guides/auth/nextcloud.md
          - Twitter: guides/auth/twitter.md
      - Migrate from Etherpad: guides/migrate-etherpad.md
      - Breaking Changes: guides/migrations-and-breaking-changes.md
      - Media Backend:
          - Minion: guides/minio-image-upload.md
          - S3: guides/s3-image-upload.md
      - Setting Terms: guides/providing-terms.md
  - Configuration: configuration.md
  - Developer:
      - API: dev/api.md
      - 'Developer Notes': dev/getting-started.md
      - 'Operational Transformation': dev/ot.md
      - Webpack: dev/webpack.md
  - FAQ: https://hedgedoc.org/faq
markdown_extensions:
  - toc:
      permalink: true
theme:
  name: 'material'
  language: en
  favicon: images/favicon.png
  logo: images/logo.png
  palette:
    scheme: preference
    primary: 'red'
    accent: 'red'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
