# SPDX-FileCopyrightText: 2026 The HedgeDoc developers (see AUTHORS file)
# SPDX-License-Identifier: AGPL-3.0-only
---
services:
  ldap:
    # renovate: datasource=docker depName=rroemhild/test-openldap
    image: rroemhild/test-openldap
    ports:
      - "10389:10389"
      - "10636:10636"
