# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: "Njsscan Analysis"

on:
  push:
    branches: [ develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]
  schedule:
    - cron: '0 7 * * 6'

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: Njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Scan with njsscan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '--sarif --output results.sarif src || true'
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
