# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Static Analysis

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 7 * * 6'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: Njsscan code scanning
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.3.1
      - name: Scan with njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@c7b65a3590ade829628b2b3c87b34ac0ce666a79 # master
        with:
          args: '--sarif --output results.sarif src || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@45c373516f557556c15d420e3f5e0aa3d64366bc # v3.31.9
        with:
          sarif_file: results.sarif

  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@45c373516f557556c15d420e3f5e0aa3d64366bc # v3.31.9
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@45c373516f557556c15d420e3f5e0aa3d64366bc # v3.31.9

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@45c373516f557556c15d420e3f5e0aa3d64366bc # v3.31.9
        with:
          category: "/language:${{ matrix.language }}"
