# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Static Analysis

on:
  push:
    branches: [ develop ]
    paths-ignore: ['docs/**']
  pull_request:
    branches: [ develop ]
    paths-ignore: ['docs/**']
  schedule:
    - cron: '0 7 * * 6'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: Njsscan code scanning
    steps:
      - name: Checkout the code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Scan with njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@74e5a58c1edb363b84c9ddd626b0e22f038ac09e # master
        with:
          args: '--sarif --output results.sarif src || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@2cb752a87e96af96708ab57187ab6372ee1973ab # v2.22.0
        with:
          sarif_file: results.sarif

  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@2cb752a87e96af96708ab57187ab6372ee1973ab # v2.22.0
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@2cb752a87e96af96708ab57187ab6372ee1973ab # v2.22.0

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@2cb752a87e96af96708ab57187ab6372ee1973ab # v2.22.0
        with:
          category: "/language:${{ matrix.language }}"
